/*
 * File:           C:\Users\shun\Desktop\CurrentProjects\CANDY\CANDY_AVB\fpga\SigmaDSP\candy_avb_IC_1_PARAM.h
 *
 * Created:        Friday, August 2, 2019 8:19:01 AM
 * Description:    candy_avb:IC 1 parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2019 Analog Devices, Inc. All rights reserved.
 */
#ifndef __CANDY_AVB_IC_1_PARAM_H__
#define __CANDY_AVB_IC_1_PARAM_H__


/* Module Modulo Size - Modulo Size*/
#define MOD_MODULOSIZE_COUNT                           1
#define MOD_MODULOSIZE_DEVICE                          "IC1"
#define MOD_MODULOSIZE_MODULO_SIZE_ADDR                0
#define MOD_MODULOSIZE_MODULO_SIZE_FIXPT               0x00001000
#define MOD_MODULOSIZE_MODULO_SIZE_VALUE               SIGMASTUDIOTYPE_INTEGER_CONVERT(4096)
#define MOD_MODULOSIZE_MODULO_SIZE_TYPE                SIGMASTUDIOTYPE_INTEGER

/* Module ph ln sw1 - Stereo Switch 2xN*/
#define MOD_PHLNSW1_COUNT                              2
#define MOD_PHLNSW1_DEVICE                             "IC1"
#define MOD_PHLNSW1_ALG0_STEREODEMUXSLEW10_ADDR        8
#define MOD_PHLNSW1_ALG0_STEREODEMUXSLEW10_FIXPT       0x00800000
#define MOD_PHLNSW1_ALG0_STEREODEMUXSLEW10_VALUE       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_PHLNSW1_ALG0_STEREODEMUXSLEW10_TYPE        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHLNSW1_ALG0_STEREODEMUXSLEW11_ADDR        9
#define MOD_PHLNSW1_ALG0_STEREODEMUXSLEW11_FIXPT       0x00000000
#define MOD_PHLNSW1_ALG0_STEREODEMUXSLEW11_VALUE       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_PHLNSW1_ALG0_STEREODEMUXSLEW11_TYPE        SIGMASTUDIOTYPE_FIXPOINT

/* Module phono eq1 - Parametric EQ*/
#define MOD_PHONOEQ1_COUNT                             30
#define MOD_PHONOEQ1_DEVICE                            "IC1"
#define MOD_PHONOEQ1_ALG0_STAGE0_B0_ADDR               10
#define MOD_PHONOEQ1_ALG0_STAGE0_B0_FIXPT              0x0084BFBA
#define MOD_PHONOEQ1_ALG0_STAGE0_B0_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.03710108693933)
#define MOD_PHONOEQ1_ALG0_STAGE0_B0_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE0_B0_ADDR               10
#define MOD_PHONOEQ1_ALG0_STAGE0_B0_FIXPT              0x0084BFBA
#define MOD_PHONOEQ1_ALG0_STAGE0_B0_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.03710108693933)
#define MOD_PHONOEQ1_ALG0_STAGE0_B0_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE0_B1_ADDR               11
#define MOD_PHONOEQ1_ALG0_STAGE0_B1_FIXPT              0xFF010E63
#define MOD_PHONOEQ1_ALG0_STAGE0_B1_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.99174848837953)
#define MOD_PHONOEQ1_ALG0_STAGE0_B1_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE0_B1_ADDR               11
#define MOD_PHONOEQ1_ALG0_STAGE0_B1_FIXPT              0xFF010E63
#define MOD_PHONOEQ1_ALG0_STAGE0_B1_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.99174848837953)
#define MOD_PHONOEQ1_ALG0_STAGE0_B1_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE0_B2_ADDR               12
#define MOD_PHONOEQ1_ALG0_STAGE0_B2_FIXPT              0x007A321C
#define MOD_PHONOEQ1_ALG0_STAGE0_B2_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.954654227074152)
#define MOD_PHONOEQ1_ALG0_STAGE0_B2_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE0_B2_ADDR               12
#define MOD_PHONOEQ1_ALG0_STAGE0_B2_FIXPT              0x007A321C
#define MOD_PHONOEQ1_ALG0_STAGE0_B2_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.954654227074152)
#define MOD_PHONOEQ1_ALG0_STAGE0_B2_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE0_A0_ADDR               13
#define MOD_PHONOEQ1_ALG0_STAGE0_A0_FIXPT              0x00FEF19D
#define MOD_PHONOEQ1_ALG0_STAGE0_A0_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.99174848837953)
#define MOD_PHONOEQ1_ALG0_STAGE0_A0_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE0_A0_ADDR               13
#define MOD_PHONOEQ1_ALG0_STAGE0_A0_FIXPT              0x00FEF19D
#define MOD_PHONOEQ1_ALG0_STAGE0_A0_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.99174848837953)
#define MOD_PHONOEQ1_ALG0_STAGE0_A0_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE0_A1_ADDR               14
#define MOD_PHONOEQ1_ALG0_STAGE0_A1_FIXPT              0xFF810E2A
#define MOD_PHONOEQ1_ALG0_STAGE0_A1_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.991755314013482)
#define MOD_PHONOEQ1_ALG0_STAGE0_A1_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE0_A1_ADDR               14
#define MOD_PHONOEQ1_ALG0_STAGE0_A1_FIXPT              0xFF810E2A
#define MOD_PHONOEQ1_ALG0_STAGE0_A1_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.991755314013482)
#define MOD_PHONOEQ1_ALG0_STAGE0_A1_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE1_B0_ADDR               15
#define MOD_PHONOEQ1_ALG0_STAGE1_B0_FIXPT              0x007E8897
#define MOD_PHONOEQ1_ALG0_STAGE1_B0_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.988543391364656)
#define MOD_PHONOEQ1_ALG0_STAGE1_B0_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE1_B0_ADDR               15
#define MOD_PHONOEQ1_ALG0_STAGE1_B0_FIXPT              0x007E8897
#define MOD_PHONOEQ1_ALG0_STAGE1_B0_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.988543391364656)
#define MOD_PHONOEQ1_ALG0_STAGE1_B0_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE1_B1_ADDR               16
#define MOD_PHONOEQ1_ALG0_STAGE1_B1_FIXPT              0xFF06BBD7
#define MOD_PHONOEQ1_ALG0_STAGE1_B1_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.94739265844841)
#define MOD_PHONOEQ1_ALG0_STAGE1_B1_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE1_B1_ADDR               16
#define MOD_PHONOEQ1_ALG0_STAGE1_B1_FIXPT              0xFF06BBD7
#define MOD_PHONOEQ1_ALG0_STAGE1_B1_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.94739265844841)
#define MOD_PHONOEQ1_ALG0_STAGE1_B1_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE1_B2_ADDR               17
#define MOD_PHONOEQ1_ALG0_STAGE1_B2_FIXPT              0x007AC3DF
#define MOD_PHONOEQ1_ALG0_STAGE1_B2_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.959102528642176)
#define MOD_PHONOEQ1_ALG0_STAGE1_B2_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE1_B2_ADDR               17
#define MOD_PHONOEQ1_ALG0_STAGE1_B2_FIXPT              0x007AC3DF
#define MOD_PHONOEQ1_ALG0_STAGE1_B2_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.959102528642176)
#define MOD_PHONOEQ1_ALG0_STAGE1_B2_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE1_A0_ADDR               18
#define MOD_PHONOEQ1_ALG0_STAGE1_A0_FIXPT              0x00F94429
#define MOD_PHONOEQ1_ALG0_STAGE1_A0_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.94739265844841)
#define MOD_PHONOEQ1_ALG0_STAGE1_A0_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE1_A0_ADDR               18
#define MOD_PHONOEQ1_ALG0_STAGE1_A0_FIXPT              0x00F94429
#define MOD_PHONOEQ1_ALG0_STAGE1_A0_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.94739265844841)
#define MOD_PHONOEQ1_ALG0_STAGE1_A0_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE1_A1_ADDR               19
#define MOD_PHONOEQ1_ALG0_STAGE1_A1_FIXPT              0xFF86B38A
#define MOD_PHONOEQ1_ALG0_STAGE1_A1_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.947645920006832)
#define MOD_PHONOEQ1_ALG0_STAGE1_A1_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE1_A1_ADDR               19
#define MOD_PHONOEQ1_ALG0_STAGE1_A1_FIXPT              0xFF86B38A
#define MOD_PHONOEQ1_ALG0_STAGE1_A1_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.947645920006832)
#define MOD_PHONOEQ1_ALG0_STAGE1_A1_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE2_B0_ADDR               20
#define MOD_PHONOEQ1_ALG0_STAGE2_B0_FIXPT              0x00338111
#define MOD_PHONOEQ1_ALG0_STAGE2_B0_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.402376321322912)
#define MOD_PHONOEQ1_ALG0_STAGE2_B0_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE2_B0_ADDR               20
#define MOD_PHONOEQ1_ALG0_STAGE2_B0_FIXPT              0x00338111
#define MOD_PHONOEQ1_ALG0_STAGE2_B0_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.402376321322912)
#define MOD_PHONOEQ1_ALG0_STAGE2_B0_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE2_B1_ADDR               21
#define MOD_PHONOEQ1_ALG0_STAGE2_B1_FIXPT              0x004A7C78
#define MOD_PHONOEQ1_ALG0_STAGE2_B1_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.58192350170784)
#define MOD_PHONOEQ1_ALG0_STAGE2_B1_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE2_B1_ADDR               21
#define MOD_PHONOEQ1_ALG0_STAGE2_B1_FIXPT              0x004A7C78
#define MOD_PHONOEQ1_ALG0_STAGE2_B1_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.58192350170784)
#define MOD_PHONOEQ1_ALG0_STAGE2_B1_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE2_B2_ADDR               22
#define MOD_PHONOEQ1_ALG0_STAGE2_B2_FIXPT              0x0022814D
#define MOD_PHONOEQ1_ALG0_STAGE2_B2_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.26957105939467)
#define MOD_PHONOEQ1_ALG0_STAGE2_B2_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE2_B2_ADDR               22
#define MOD_PHONOEQ1_ALG0_STAGE2_B2_FIXPT              0x0022814D
#define MOD_PHONOEQ1_ALG0_STAGE2_B2_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.26957105939467)
#define MOD_PHONOEQ1_ALG0_STAGE2_B2_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE2_A0_ADDR               23
#define MOD_PHONOEQ1_ALG0_STAGE2_A0_FIXPT              0xFFB58388
#define MOD_PHONOEQ1_ALG0_STAGE2_A0_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.58192350170784)
#define MOD_PHONOEQ1_ALG0_STAGE2_A0_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE2_A0_ADDR               23
#define MOD_PHONOEQ1_ALG0_STAGE2_A0_FIXPT              0xFFB58388
#define MOD_PHONOEQ1_ALG0_STAGE2_A0_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.58192350170784)
#define MOD_PHONOEQ1_ALG0_STAGE2_A0_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE2_A1_ADDR               24
#define MOD_PHONOEQ1_ALG0_STAGE2_A1_FIXPT              0x0029FDA0
#define MOD_PHONOEQ1_ALG0_STAGE2_A1_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.328052619282417)
#define MOD_PHONOEQ1_ALG0_STAGE2_A1_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOEQ1_ALG0_STAGE2_A1_ADDR               24
#define MOD_PHONOEQ1_ALG0_STAGE2_A1_FIXPT              0x0029FDA0
#define MOD_PHONOEQ1_ALG0_STAGE2_A1_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.328052619282417)
#define MOD_PHONOEQ1_ALG0_STAGE2_A1_TYPE               SIGMASTUDIOTYPE_FIXPOINT

/* Module master gain - Single SW slew vol (adjustable)*/
#define MOD_MASTERGAIN_COUNT                           2
#define MOD_MASTERGAIN_DEVICE                          "IC1"
#define MOD_MASTERGAIN_ALG0_TARGET_ADDR                25
#define MOD_MASTERGAIN_ALG0_TARGET_FIXPT               0x00800000
#define MOD_MASTERGAIN_ALG0_TARGET_VALUE               SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MASTERGAIN_ALG0_TARGET_TYPE                SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MASTERGAIN_ALG0_STEP_ADDR                  26
#define MOD_MASTERGAIN_ALG0_STEP_FIXPT                 0x00008000
#define MOD_MASTERGAIN_ALG0_STEP_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00390625)
#define MOD_MASTERGAIN_ALG0_STEP_TYPE                  SIGMASTUDIOTYPE_FIXPOINT

/* Module phono gain1 - Single SW slew vol (adjustable)*/
#define MOD_PHONOGAIN1_COUNT                           2
#define MOD_PHONOGAIN1_DEVICE                          "IC1"
#define MOD_PHONOGAIN1_ALG0_TARGET_ADDR                27
#define MOD_PHONOGAIN1_ALG0_TARGET_FIXPT               0x07ECA9CD
#define MOD_PHONOGAIN1_ALG0_TARGET_VALUE               SIGMASTUDIOTYPE_FIXPOINT_CONVERT(15.8489319246111)
#define MOD_PHONOGAIN1_ALG0_TARGET_TYPE                SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PHONOGAIN1_ALG0_STEP_ADDR                  28
#define MOD_PHONOGAIN1_ALG0_STEP_FIXPT                 0x00008000
#define MOD_PHONOGAIN1_ALG0_STEP_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00390625)
#define MOD_PHONOGAIN1_ALG0_STEP_TYPE                  SIGMASTUDIOTYPE_FIXPOINT

/* Module Mid EQ1 - Medium Size Eq*/
#define MOD_MIDEQ1_COUNT                               9
#define MOD_MIDEQ1_DEVICE                              "IC1"
#define MOD_MIDEQ1_ALG0_STAGE0_B2_ADDR                 29
#define MOD_MIDEQ1_ALG0_STAGE0_B2_FIXPT                0x007DCB85
#define MOD_MIDEQ1_ALG0_STAGE0_B2_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.982773457391717)
#define MOD_MIDEQ1_ALG0_STAGE0_B2_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE0_B1_ADDR                 30
#define MOD_MIDEQ1_ALG0_STAGE0_B1_FIXPT                0xFF0462B4
#define MOD_MIDEQ1_ALG0_STAGE0_B1_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.96573791559061)
#define MOD_MIDEQ1_ALG0_STAGE0_B1_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE0_B0_ADDR                 31
#define MOD_MIDEQ1_ALG0_STAGE0_B0_FIXPT                0x007DD1C7
#define MOD_MIDEQ1_ALG0_STAGE0_B0_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.982964476761079)
#define MOD_MIDEQ1_ALG0_STAGE0_B0_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE0_A2_ADDR                 32
#define MOD_MIDEQ1_ALG0_STAGE0_A2_FIXPT                0xFF845916
#define MOD_MIDEQ1_ALG0_STAGE0_A2_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.966031418854412)
#define MOD_MIDEQ1_ALG0_STAGE0_A2_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_STAGE0_A1_ADDR                 33
#define MOD_MIDEQ1_ALG0_STAGE0_A1_FIXPT                0x00FB93AE
#define MOD_MIDEQ1_ALG0_STAGE0_A1_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.96544443088901)
#define MOD_MIDEQ1_ALG0_STAGE0_A1_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MIDEQ1_ALG0_DATA_ADR_ADDR                  34
#define MOD_MIDEQ1_ALG0_DATA_ADR_FIXPT                 0x0000004C
#define MOD_MIDEQ1_ALG0_DATA_ADR_VALUE                 SIGMASTUDIOTYPE_INTEGER_CONVERT(76)
#define MOD_MIDEQ1_ALG0_DATA_ADR_TYPE                  SIGMASTUDIOTYPE_INTEGER
#define MOD_MIDEQ1_ALG0_DATAR_ADR_ADDR                 35
#define MOD_MIDEQ1_ALG0_DATAR_ADR_FIXPT                0x00000055
#define MOD_MIDEQ1_ALG0_DATAR_ADR_VALUE                SIGMASTUDIOTYPE_INTEGER_CONVERT(85)
#define MOD_MIDEQ1_ALG0_DATAR_ADR_TYPE                 SIGMASTUDIOTYPE_INTEGER
#define MOD_MIDEQ1_ALG0_COEFF_ADR_ADDR                 36
#define MOD_MIDEQ1_ALG0_COEFF_ADR_FIXPT                0x00000020
#define MOD_MIDEQ1_ALG0_COEFF_ADR_VALUE                SIGMASTUDIOTYPE_INTEGER_CONVERT(32)
#define MOD_MIDEQ1_ALG0_COEFF_ADR_TYPE                 SIGMASTUDIOTYPE_INTEGER
#define MOD_MIDEQ1_ALG0_LOOP_ADDR                      37
#define MOD_MIDEQ1_ALG0_LOOP_FIXPT                     0x00000001
#define MOD_MIDEQ1_ALG0_LOOP_VALUE                     SIGMASTUDIOTYPE_INTEGER_CONVERT(1)
#define MOD_MIDEQ1_ALG0_LOOP_TYPE                      SIGMASTUDIOTYPE_INTEGER

/* Module Mg1 - Signal Merger*/
#define MOD_MG1_COUNT                                  1
#define MOD_MG1_DEVICE                                 "IC1"
#define MOD_MG1_SINGLECTRLMIXER19401_ADDR              38
#define MOD_MG1_SINGLECTRLMIXER19401_FIXPT             0x00400000
#define MOD_MG1_SINGLECTRLMIXER19401_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.5)
#define MOD_MG1_SINGLECTRLMIXER19401_TYPE              SIGMASTUDIOTYPE_FIXPOINT

/* Module Mg3 - Signal Merger*/
#define MOD_MG3_COUNT                                  1
#define MOD_MG3_DEVICE                                 "IC1"
#define MOD_MG3_SINGLECTRLMIXER19402_ADDR              39
#define MOD_MG3_SINGLECTRLMIXER19402_FIXPT             0x00400000
#define MOD_MG3_SINGLECTRLMIXER19402_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.5)
#define MOD_MG3_SINGLECTRLMIXER19402_TYPE              SIGMASTUDIOTYPE_FIXPOINT

/* Module gain1 - Single SW slew vol (adjustable)*/
#define MOD_GAIN1_COUNT                                2
#define MOD_GAIN1_DEVICE                               "IC1"
#define MOD_GAIN1_ALG0_TARGET_ADDR                     40
#define MOD_GAIN1_ALG0_TARGET_FIXPT                    0x00800000
#define MOD_GAIN1_ALG0_TARGET_VALUE                    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_GAIN1_ALG0_TARGET_TYPE                     SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GAIN1_ALG0_STEP_ADDR                       41
#define MOD_GAIN1_ALG0_STEP_FIXPT                      0x00008000
#define MOD_GAIN1_ALG0_STEP_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00390625)
#define MOD_GAIN1_ALG0_STEP_TYPE                       SIGMASTUDIOTYPE_FIXPOINT

/* Module eq1 - Medium Size Eq*/
#define MOD_EQ1_COUNT                                  27
#define MOD_EQ1_DEVICE                                 "IC1"
#define MOD_EQ1_ALG0_STAGE0_B2_ADDR                    42
#define MOD_EQ1_ALG0_STAGE0_B2_FIXPT                   0x0027245F
#define MOD_EQ1_ALG0_STAGE0_B2_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.305797522864985)
#define MOD_EQ1_ALG0_STAGE0_B2_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ1_ALG0_STAGE0_B1_ADDR                    43
#define MOD_EQ1_ALG0_STAGE0_B1_FIXPT                   0xFF91CBAB
#define MOD_EQ1_ALG0_STAGE0_B1_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.860972132069065)
#define MOD_EQ1_ALG0_STAGE0_B1_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ1_ALG0_STAGE0_B0_ADDR                    44
#define MOD_EQ1_ALG0_STAGE0_B0_FIXPT                   0x00800000
#define MOD_EQ1_ALG0_STAGE0_B0_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_EQ1_ALG0_STAGE0_B0_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ1_ALG0_STAGE0_A2_ADDR                    45
#define MOD_EQ1_ALG0_STAGE0_A2_FIXPT                   0xFFD8DBA1
#define MOD_EQ1_ALG0_STAGE0_A2_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.305797522864985)
#define MOD_EQ1_ALG0_STAGE0_A2_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ1_ALG0_STAGE0_A1_ADDR                    46
#define MOD_EQ1_ALG0_STAGE0_A1_FIXPT                   0x006E3455
#define MOD_EQ1_ALG0_STAGE0_A1_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.860972132069065)
#define MOD_EQ1_ALG0_STAGE0_A1_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ1_ALG0_STAGE1_B2_ADDR                    47
#define MOD_EQ1_ALG0_STAGE1_B2_FIXPT                   0x00000000
#define MOD_EQ1_ALG0_STAGE1_B2_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ1_ALG0_STAGE1_B2_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ1_ALG0_STAGE1_B1_ADDR                    48
#define MOD_EQ1_ALG0_STAGE1_B1_FIXPT                   0x00000000
#define MOD_EQ1_ALG0_STAGE1_B1_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ1_ALG0_STAGE1_B1_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ1_ALG0_STAGE1_B0_ADDR                    49
#define MOD_EQ1_ALG0_STAGE1_B0_FIXPT                   0x00800000
#define MOD_EQ1_ALG0_STAGE1_B0_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_EQ1_ALG0_STAGE1_B0_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ1_ALG0_STAGE1_A2_ADDR                    50
#define MOD_EQ1_ALG0_STAGE1_A2_FIXPT                   0x00000000
#define MOD_EQ1_ALG0_STAGE1_A2_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ1_ALG0_STAGE1_A2_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ1_ALG0_STAGE1_A1_ADDR                    51
#define MOD_EQ1_ALG0_STAGE1_A1_FIXPT                   0x00000000
#define MOD_EQ1_ALG0_STAGE1_A1_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_EQ1_ALG0_STAGE1_A1_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ1_ALG0_STAGE2_B2_ADDR                    52
#define MOD_EQ1_ALG0_STAGE2_B2_FIXPT                   0x007B58FB
#define MOD_EQ1_ALG0_STAGE2_B2_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.963652984223705)
#define MOD_EQ1_ALG0_STAGE2_B2_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ1_ALG0_STAGE2_B1_ADDR                    53
#define MOD_EQ1_ALG0_STAGE2_B1_FIXPT                   0xFF04BD12
#define MOD_EQ1_ALG0_STAGE2_B1_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.96298008938934)
#define MOD_EQ1_ALG0_STAGE2_B1_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ1_ALG0_STAGE2_B0_ADDR                    54
#define MOD_EQ1_ALG0_STAGE2_B0_FIXPT                   0x00800000
#define MOD_EQ1_ALG0_STAGE2_B0_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_EQ1_ALG0_STAGE2_B0_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ1_ALG0_STAGE2_A2_ADDR                    55
#define MOD_EQ1_ALG0_STAGE2_A2_FIXPT                   0xFF84A705
#define MOD_EQ1_ALG0_STAGE2_A2_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.963652984223705)
#define MOD_EQ1_ALG0_STAGE2_A2_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ1_ALG0_STAGE2_A1_ADDR                    56
#define MOD_EQ1_ALG0_STAGE2_A1_FIXPT                   0x00FB42EE
#define MOD_EQ1_ALG0_STAGE2_A1_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.96298008938934)
#define MOD_EQ1_ALG0_STAGE2_A1_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_EQ1_ALG0_DATA_ADR_ADDR                     57
#define MOD_EQ1_ALG0_DATA_ADR_FIXPT                    0x00000069
#define MOD_EQ1_ALG0_DATA_ADR_VALUE                    SIGMASTUDIOTYPE_INTEGER_CONVERT(105)
#define MOD_EQ1_ALG0_DATA_ADR_TYPE                     SIGMASTUDIOTYPE_INTEGER
#define MOD_EQ1_ALG0_DATA_ADR_ADDR                     57
#define MOD_EQ1_ALG0_DATA_ADR_FIXPT                    0x00000069
#define MOD_EQ1_ALG0_DATA_ADR_VALUE                    SIGMASTUDIOTYPE_INTEGER_CONVERT(105)
#define MOD_EQ1_ALG0_DATA_ADR_TYPE                     SIGMASTUDIOTYPE_INTEGER
#define MOD_EQ1_ALG0_DATA_ADR_ADDR                     57
#define MOD_EQ1_ALG0_DATA_ADR_FIXPT                    0x00000069
#define MOD_EQ1_ALG0_DATA_ADR_VALUE                    SIGMASTUDIOTYPE_INTEGER_CONVERT(105)
#define MOD_EQ1_ALG0_DATA_ADR_TYPE                     SIGMASTUDIOTYPE_INTEGER
#define MOD_EQ1_ALG0_DATAR_ADR_ADDR                    58
#define MOD_EQ1_ALG0_DATAR_ADR_FIXPT                   0x0000007E
#define MOD_EQ1_ALG0_DATAR_ADR_VALUE                   SIGMASTUDIOTYPE_INTEGER_CONVERT(126)
#define MOD_EQ1_ALG0_DATAR_ADR_TYPE                    SIGMASTUDIOTYPE_INTEGER
#define MOD_EQ1_ALG0_DATAR_ADR_ADDR                    58
#define MOD_EQ1_ALG0_DATAR_ADR_FIXPT                   0x0000007E
#define MOD_EQ1_ALG0_DATAR_ADR_VALUE                   SIGMASTUDIOTYPE_INTEGER_CONVERT(126)
#define MOD_EQ1_ALG0_DATAR_ADR_TYPE                    SIGMASTUDIOTYPE_INTEGER
#define MOD_EQ1_ALG0_DATAR_ADR_ADDR                    58
#define MOD_EQ1_ALG0_DATAR_ADR_FIXPT                   0x0000007E
#define MOD_EQ1_ALG0_DATAR_ADR_VALUE                   SIGMASTUDIOTYPE_INTEGER_CONVERT(126)
#define MOD_EQ1_ALG0_DATAR_ADR_TYPE                    SIGMASTUDIOTYPE_INTEGER
#define MOD_EQ1_ALG0_COEFF_ADR_ADDR                    59
#define MOD_EQ1_ALG0_COEFF_ADR_FIXPT                   0x0000002D
#define MOD_EQ1_ALG0_COEFF_ADR_VALUE                   SIGMASTUDIOTYPE_INTEGER_CONVERT(45)
#define MOD_EQ1_ALG0_COEFF_ADR_TYPE                    SIGMASTUDIOTYPE_INTEGER
#define MOD_EQ1_ALG0_COEFF_ADR_ADDR                    59
#define MOD_EQ1_ALG0_COEFF_ADR_FIXPT                   0x0000002D
#define MOD_EQ1_ALG0_COEFF_ADR_VALUE                   SIGMASTUDIOTYPE_INTEGER_CONVERT(45)
#define MOD_EQ1_ALG0_COEFF_ADR_TYPE                    SIGMASTUDIOTYPE_INTEGER
#define MOD_EQ1_ALG0_COEFF_ADR_ADDR                    59
#define MOD_EQ1_ALG0_COEFF_ADR_FIXPT                   0x0000002D
#define MOD_EQ1_ALG0_COEFF_ADR_VALUE                   SIGMASTUDIOTYPE_INTEGER_CONVERT(45)
#define MOD_EQ1_ALG0_COEFF_ADR_TYPE                    SIGMASTUDIOTYPE_INTEGER
#define MOD_EQ1_ALG0_LOOP_ADDR                         60
#define MOD_EQ1_ALG0_LOOP_FIXPT                        0x00000003
#define MOD_EQ1_ALG0_LOOP_VALUE                        SIGMASTUDIOTYPE_INTEGER_CONVERT(3)
#define MOD_EQ1_ALG0_LOOP_TYPE                         SIGMASTUDIOTYPE_INTEGER
#define MOD_EQ1_ALG0_LOOP_ADDR                         60
#define MOD_EQ1_ALG0_LOOP_FIXPT                        0x00000003
#define MOD_EQ1_ALG0_LOOP_VALUE                        SIGMASTUDIOTYPE_INTEGER_CONVERT(3)
#define MOD_EQ1_ALG0_LOOP_TYPE                         SIGMASTUDIOTYPE_INTEGER
#define MOD_EQ1_ALG0_LOOP_ADDR                         60
#define MOD_EQ1_ALG0_LOOP_FIXPT                        0x00000003
#define MOD_EQ1_ALG0_LOOP_VALUE                        SIGMASTUDIOTYPE_INTEGER_CONVERT(3)
#define MOD_EQ1_ALG0_LOOP_TYPE                         SIGMASTUDIOTYPE_INTEGER

#endif
